class CommMessageTypes:
  HEART_BEAT = 1
  MEMORY_HEADER = 2
  MEMORY_DATA = 3
  THREADS_HEADER = 5
  THREADS_SELECT_LINES = 6
  LOG_TEXT = 7
  IMAGE = 8
  FOOTSTEPS = 9
  PF_STATES = 10
  NIHA_COGNITION_HEADER = 11
  NIHA_COGNITION_DATA = 12