/**
 * @file Utils/include/HardwareIds.h
 *
 * This file declares the enumeration ids for all the sensors and
 * actuators of the robot
 *
 * @author <A href="mailto:saifullah3396@gmailcom">Saifullah</A>
 * @date 1 Jan 2017
 */

#pragma once

/**
 * Enumeration for available joint sensor types
 *
 * @enum JointSensorTypes
 */
enum JointSensorTypes
{
  POSITION = 0,
  TEMPERATURE,
  //TEMP_STATUS,
  CURRENT,
  HARDNESS_SENSOR,
  NUM_JOINT_SENSOR_TYPES
};

/**
 * Enumeration for available sensor types
 *
 * @enum SensorTypes
 */
enum SensorTypes
{
  JOINTS = 0,
  TOUCH_SENSORS = NUM_JOINT_SENSOR_TYPES,
  SWITCH_SENSORS,
  BATTERY_SENSORS,
  INERTIAL_SENSORS,
  SONAR_SENSORS,
  FSR_SENSORS,
  LED_SENSORS,
  NUM_SENSOR_TYPES
};

/**
 * Enumeration for available joint actuator types
 *
 * @enum JointActuatorTypes
 */
enum JointActuatorTypes
{
  ANGLES = 0,
  HARDNESS,
  NUM_JOINT_ACTUATOR_TYPES
};

/**
 * Enumeration for available actuator types
 *
 * @enum ActuatorTypes
 */

enum ActuatorTypes
{
  JOINT_ACTUATORS = 0,
  LED_ACTUATORS = NUM_JOINT_ACTUATOR_TYPES,
  NUM_ACTUATOR_TYPES
};

/**
 * Enumeration for available sensors
 *
 * @enum HardwareIds
 */

enum HardwareIds
{
  //!Joints
  HEAD_YAW = 0,
  HEAD_PITCH,
  HEAD_END,
  HEAD_SIZE = HEAD_END,
  L_SHOULDER_PITCH = HEAD_END,
  L_SHOULDER_ROLL,
  L_ELBOW_YAW,
  L_ELBOW_ROLL,
  L_WRIST_YAW,
  //L_HAND_POSITION,
  L_ARM_END,
  L_ARM_SIZE = L_ARM_END - HEAD_END,
  R_SHOULDER_PITCH = L_ARM_END,
  R_SHOULDER_ROLL,
  R_ELBOW_YAW,
  R_ELBOW_ROLL,
  R_WRIST_YAW,
  //R_HAND_POSITION,
  R_ARM_END,
  R_ARM_SIZE = R_ARM_END - L_ARM_END,
  L_HIP_YAW_PITCH = R_ARM_END,
  L_HIP_ROLL,
  L_HIP_PITCH,
  L_KNEE_PITCH,
  L_ANKLE_PITCH,
  L_ANKLE_ROLL,
  L_LEG_END,
  L_LEG_SIZE = L_LEG_END - R_ARM_END,
  R_HIP_YAW_PITCH = L_LEG_END,
  R_HIP_ROLL,
  R_HIP_PITCH,
  R_KNEE_PITCH,
  R_ANKLE_PITCH,
  R_ANKLE_ROLL,
  R_LEG_END,
  R_LEG_SIZE = R_LEG_END - L_LEG_END,
  NUM_JOINTS = R_LEG_END,
  TORSO = NUM_JOINTS,
  NUM_LINKS,

  //!Touch Sensors
  HEAD_TOUCH_FRONT = 0,
  HEAD_TOUCH_REAR,
  HEAD_TOUCH_MIDDLE,
  L_HAND_TOUCH_BACK,
  L_HAND_TOUCH_LEFT,
  L_HAND_TOUCH_RIGHT,
  R_HAND_TOUCH_BACK,
  R_HAND_TOUCH_LEFT,
  R_HAND_TOUCH_RIGHT,
  NUM_TOUCH_SENSORS,

  //!Switch Sensors
  CHEST_BOARD_BUTTON = 0,
  L_FOOT_BUMPER_RIGHT,
  L_FOOT_BUMPER_LEFT,
  R_FOOT_BUMPER_RIGHT,
  R_FOOT_BUMPER_LEFT,
  NUM_SWITCH_SENSORS,

  ///!Battery Sensors
  HEAD_CPU_TEMPERATURE = 0,
  BATTERY_CURRENT,
  BATTERY_CHARGE,
  BATTERY_TEMPERATURE,
  NUM_BATTERY_SENSORS,

  //!Inertial Sensors
  GYROSCOPE_X = 0,
  GYROSCOPE_Y,
  GYROSCOPE_Z,
  TORSO_ANGLE_X,
  TORSO_ANGLE_Y,
  TORSO_ANGLE_Z,
  ACCELEROMETER_X,
  ACCELEROMETER_Y,
  ACCELEROMETER_Z,
  NUM_INERTIAL_SENSORS,

  //!Sonar Sensors
  L_US_SONAR = 0,
  L_US_SONAR_1,
  L_US_SONAR_2,
  L_US_SONAR_3,
  L_US_SONAR_4,
  L_US_SONAR_5,
  L_US_SONAR_6,
  L_US_SONAR_7,
  L_US_SONAR_8,
  L_US_SONAR_9,
  R_US_SONAR,
  R_US_SONAR_1,
  R_US_SONAR_2,
  R_US_SONAR_3,
  R_US_SONAR_4,
  R_US_SONAR_5,
  R_US_SONAR_6,
  R_US_SONAR_7,
  R_US_SONAR_8,
  R_US_SONAR_9,
  NUM_SONAR_SENSORS,

  //!Fsr Sensors
  L_FOOT_FSR_FL = 0,
  L_FOOT_FSR_FR,
  L_FOOT_FSR_RL,
  L_FOOT_FSR_RR,
  L_FOOT_TOTAL_WEIGHT,
  L_FOOT_COP_X,
  L_FOOT_COP_Y,
  R_FOOT_FSR_FL,
  R_FOOT_FSR_FR,
  R_FOOT_FSR_RL,
  R_FOOT_FSR_RR,
  R_FOOT_TOTAL_WEIGHT,
  R_FOOT_COP_X,
  R_FOOT_COP_Y,
  NUM_FSR_SENSORS,

  //!Led Actuators
  FACE_LED_RED_LEFT_0_DEG_ACTUATOR = 0,
  FACE_LED_RED_LEFT_45_DEG_ACTUATOR,
  FACE_LED_RED_LEFT_90_DEG_ACTUATOR,
  FACE_LED_RED_LEFT_135_DEG_ACTUATOR,
  FACE_LED_RED_LEFT_180_DEG_ACTUATOR,
  FACE_LED_RED_LEFT_225_DEG_ACTUATOR,
  FACE_LED_RED_LEFT_270_DEG_ACTUATOR,
  FACE_LED_RED_LEFT_315_DEG_ACTUATOR,
  FACE_LED_GREEN_LEFT_0_DEG_ACTUATOR,
  FACE_LED_GREEN_LEFT_45_DEG_ACTUATOR,
  FACE_LED_GREEN_LEFT_90_DEG_ACTUATOR,
  FACE_LED_GREEN_LEFT_135_DEG_ACTUATOR,
  FACE_LED_GREEN_LEFT_180_DEG_ACTUATOR,
  FACE_LED_GREEN_LEFT_225_DEG_ACTUATOR,
  FACE_LED_GREEN_LEFT_270_DEG_ACTUATOR,
  FACE_LED_GREEN_LEFT_315_DEG_ACTUATOR,
  FACE_LED_BLUE_LEFT_0_DEG_ACTUATOR,
  FACE_LED_BLUE_LEFT_45_DEG_ACTUATOR,
  FACE_LED_BLUE_LEFT_90_DEG_ACTUATOR,
  FACE_LED_BLUE_LEFT_135_DEG_ACTUATOR,
  FACE_LED_BLUE_LEFT_180_DEG_ACTUATOR,
  FACE_LED_BLUE_LEFT_225_DEG_ACTUATOR,
  FACE_LED_BLUE_LEFT_270_DEG_ACTUATOR,
  FACE_LED_BLUE_LEFT_315_DEG_ACTUATOR,
  END_FACE_L_LED,
  NUM_FACE_L_LED = END_FACE_L_LED,
  FACE_LED_RED_RIGHT_0_DEG_ACTUATOR = END_FACE_L_LED,
  FACE_LED_RED_RIGHT_45_DEG_ACTUATOR,
  FACE_LED_RED_RIGHT_90_DEG_ACTUATOR,
  FACE_LED_RED_RIGHT_135_DEG_ACTUATOR,
  FACE_LED_RED_RIGHT_180_DEG_ACTUATOR,
  FACE_LED_RED_RIGHT_225_DEG_ACTUATOR,
  FACE_LED_RED_RIGHT_270_DEG_ACTUATOR,
  FACE_LED_RED_RIGHT_315_DEG_ACTUATOR,
  FACE_LED_GREEN_RIGHT_0_DEG_ACTUATOR,
  FACE_LED_GREEN_RIGHT_45_DEG_ACTUATOR,
  FACE_LED_GREEN_RIGHT_90_DEG_ACTUATOR,
  FACE_LED_GREEN_RIGHT_135_DEG_ACTUATOR,
  FACE_LED_GREEN_RIGHT_180_DEG_ACTUATOR,
  FACE_LED_GREEN_RIGHT_225_DEG_ACTUATOR,
  FACE_LED_GREEN_RIGHT_270_DEG_ACTUATOR,
  FACE_LED_GREEN_RIGHT_315_DEG_ACTUATOR,
  FACE_LED_BLUE_RIGHT_0_DEG_ACTUATOR,
  FACE_LED_BLUE_RIGHT_45_DEG_ACTUATOR,
  FACE_LED_BLUE_RIGHT_90_DEG_ACTUATOR,
  FACE_LED_BLUE_RIGHT_135_DEG_ACTUATOR,
  FACE_LED_BLUE_RIGHT_180_DEG_ACTUATOR,
  FACE_LED_BLUE_RIGHT_225_DEG_ACTUATOR,
  FACE_LED_BLUE_RIGHT_270_DEG_ACTUATOR,
  FACE_LED_BLUE_RIGHT_315_DEG_ACTUATOR,
  END_FACE_R_LED,
  NUM_FACE_R_LED = END_FACE_R_LED - END_FACE_L_LED,
  EARS_LED_LEFT_0_DEG_ACTUATOR = END_FACE_R_LED,
  EARS_LED_LEFT_36_DEG_ACTUATOR,
  EARS_LED_LEFT_72_DEG_ACTUATOR,
  EARS_LED_LEFT_108_DEG_ACTUATOR,
  EARS_LED_LEFT_144_DEG_ACTUATOR,
  EARS_LED_LEFT_180_DEG_ACTUATOR,
  EARS_LED_LEFT_216_DEG_ACTUATOR,
  EARS_LED_LEFT_252_DEG_ACTUATOR,
  EARS_LED_LEFT_288_DEG_ACTUATOR,
  EARS_LED_LEFT_324_DEG_ACTUATOR,
  END_EL_LED,
  NUM_EL_LED = END_EL_LED - END_FACE_R_LED,
  EARS_LED_RIGHT_0_DEG_ACTUATOR = END_EL_LED,
  EARS_LED_RIGHT_36_DEG_ACTUATOR,
  EARS_LED_RIGHT_72_DEG_ACTUATOR,
  EARS_LED_RIGHT_108_DEG_ACTUATOR,
  EARS_LED_RIGHT_144_DEG_ACTUATOR,
  EARS_LED_RIGHT_180_DEG_ACTUATOR,
  EARS_LED_RIGHT_216_DEG_ACTUATOR,
  EARS_LED_RIGHT_252_DEG_ACTUATOR,
  EARS_LED_RIGHT_288_DEG_ACTUATOR,
  EARS_LED_RIGHT_324_DEG_ACTUATOR,
  END_ER_LED,
  NUM_ER_LED = END_ER_LED - END_EL_LED,
  CHEST_BOARD_LED_RED_ACTUATOR = END_ER_LED,
  CHEST_BOARD_LED_GREEN_ACTUATOR,
  CHEST_BOARD_LED_BLUE_ACTUATOR,
  END_C_LED,
  NUM_C_LED = END_C_LED - END_ER_LED,
  HEAD_LED_REAR_LEFT_0_ACTUATOR = END_C_LED,
  HEAD_LED_REAR_LEFT_1_ACTUATOR,
  HEAD_LED_REAR_LEFT_2_ACTUATOR,
  END_HRL_LED,
  NUM_HRL_LED = END_HRL_LED - END_C_LED,
  HEAD_LED_REAR_RIGHT_0_ACTUATOR = END_HRL_LED,
  HEAD_LED_REAR_RIGHT_1_ACTUATOR,
  HEAD_LED_REAR_RIGHT_2_ACTUATOR,
  END_HRR_LED,
  NUM_HRR_LED = END_HRR_LED - END_HRL_LED,
  HEAD_LED_FRONT_RIGHT_0_ACTUATOR = END_HRR_LED,
  HEAD_LED_FRONT_RIGHT_1_ACTUATOR,
  END_HFR_LED,
  NUM_HFR_LED = END_HFR_LED - END_HRR_LED,
  HEAD_LED_FRONT_LEFT_0_ACTUATOR = END_HFR_LED,
  HEAD_LED_FRONT_LEFT_1_ACTUATOR,
  END_HFL_LED,
  NUM_HFL_LED = END_HFL_LED - END_HFR_LED,
  HEAD_LED_MIDDLE_RIGHT_0_ACTUATOR = END_HFL_LED,
  HEAD_LED_MIDDLE_LEFT_0_ACTUATOR,
  END_HM_LED,
  NUM_HM_LED = END_HM_LED - END_HFL_LED,
  NUM_HEAD_LED = END_HM_LED - END_C_LED,
  L_FOOT_LED_RED_ACTUATOR = END_HM_LED,
  L_FOOT_LED_GREEN_ACTUATOR,
  L_FOOT_LED_BLUE_ACTUATOR,
  END_L_FEET_LED,
  NUM_L_FEET_LED = END_L_FEET_LED - END_HM_LED,
  R_FOOT_LED_RED_ACTUATOR = END_L_FEET_LED,
  R_FOOT_LED_GREEN_ACTUATOR,
  R_FOOT_LED_BLUE_ACTUATOR,
  END_R_FEET_LED,
  NUM_R_FEET_LED = END_R_FEET_LED - END_L_FEET_LED,
  NUM_LED_ACTUATORS = END_R_FEET_LED,
};

/**
 * Enumerator for the robot link chains
 *
 * @enum LinkChains
 */
enum LinkChains
{
  CHAIN_HEAD = 0,
  CHAIN_L_ARM,
  CHAIN_R_ARM,
  CHAIN_L_LEG,
  CHAIN_R_LEG,
  CHAINS_SIZE
};

enum class LedGroups : unsigned int
{
  HEAD = 0,
  L_FACE,
  R_FACE,
  L_EAR,
  R_EAR,
  CHEST,
  L_FEET,
  R_FEET,
  NUM_LED_GROUPS
};

/**
 * Enumerator for the robot cameras
 *
 * @enum Cameras
 */
enum Cameras
{
  TOP_CAM = 0,
  BOTTOM_CAM,
  NUM_CAMS
};

/**
 * Enumerator for the hands of the robot
 *
 * @enum RobotHands
 */
enum RobotHands
{
  L_HAND = 0,
  R_HAND,
  NUM_HANDS
};

/**
 * Enumerator for the feet of the robot
 *
 * @enum RobotFeet
 */
enum RobotFeet
{
  L_FOOT = 0,
  R_FOOT,
  NUM_FOOT
};

/**
 * Enumerator for the used robot leg end effectors
 *
 * @enum LegEEs
 */
enum LegEEs
{
  ANKLE = 0,
  FEET_BASE,
  KICK_EE,
  NUM_LEG_EES
};
